language: perl
perl:
- '5.22'
- '5.20'
- '5.18'
- '5.16'
- '5.14'
notifications:
  slack:
    secure: nK3ZRr6LsWu2mmNG7095XyWZmmI+5W3mXja0iMRPeHr1N2758tO4hCIUp65UJ03qggKXDTNEuJxhvd1kKdkHYqUPCGbZRhowzdwpQQGz2HH7124BIXHKNCuSf7ilU3ZtYPON7nj9pj125O7297rzcw6issbkWjK5hMOra4HAiMQu/X2kdNxRURxG3LvAi/7zvykFpAPHceDw8MkRr13+Ep7J1AhdcelpkyJZ6p2pqWxysbIDdDK/bSYEXYTO0ubV6cMjRfKE9oVG0Gbuj3O3ww6UfTCnG4yFFflYYDJ+BgQv+Yruf07wLyhF2Rgi5GoZCfFLknjk5oNkuADz8LRy1EJMQi2RpjT1qhQTJAEkjVefku9GV6K8iEkmdtLh5GKKuOOQyESduWG0tqn1cObadvUEA24IRip8AD4myrM7TAaUTkCuyaPjp9+AXnZp75mkdvGljAWMtQ+0l5mf+nifMGwCfu7InIQDZBuse55n/OdxvRwtHD0cjHKZTWYCQW6Y48KvT3CbUiRF+8rTrkkq6lnkeE4lWhsM0JMUHEKd/aRyDRI5Uzf/y9n/Rw9NxQcSlbPmGD5DfvAZ/ufvLWeJbDOG2LhPn2/PmlDXa5Bfvp+7DEMeMK0XGMYo9QEL5jAWQZEtMhXz6CeO2SLJH0iB7iXKin0pHW9s4yxnLCQo9/A=
